services:
  postgres:
    image: postgres:16-alpine
    container_name: om-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: om_admin
      POSTGRES_PASSWORD: om_password
      POSTGRES_DB: order_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: om-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq:latest
    container_name: om-seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"

volumes:
  postgres_data:


